/// Profile trait — defines the shape of a knowledge base for a specific
/// context (for-coding, for-design, for-research, etc.).
///
/// Each profile declares what directories to create, what seed files to
/// write, and what AGENTS.md label to use.
///
/// # Implementing a new profile
///
/// ```rust
/// use enjoyknowledge::core::Profile;
///
/// struct DesignProfile;
///
/// impl Profile for DesignProfile {
///     fn name(&self) -> &str { "for-design" }
///     fn directories(&self) -> Vec<&str> {
///         vec!["components", "tokens", "guidelines", "assets"]
///     }
///     fn seed_files(&self) -> Vec<(&str, &str)> { vec![] }
///     fn agents_md_label(&self) -> &str { "design" }
/// }
/// ```
#[allow(dead_code)]
pub trait Profile {
    /// Unique profile identifier (e.g. `"for-coding"`).
    fn name(&self) -> &str;

    /// Subdirectory names to create under `.enjoyknowledge/`.
    fn directories(&self) -> Vec<&str>;

    /// Optional seed files: `(relative_path_under_enjoyknowledge, markdown_content)`.
    /// Only written if the file does not already exist.
    fn seed_files(&self) -> Vec<(&str, &str)>;

    /// Label inserted into AGENTS.md footer (`Generated by enjoyknowledge init --template {label}`).
    fn agents_md_label(&self) -> &str;
}
