/// `for-coding` profile -- 11 knowledge categories for general software
/// development projects.
///
/// Directories (v0.4.3+):
/// - `architecture` -- system design, module map, data flow
/// - `business`     -- domain rules, compliance, billing logic
/// - `command`      -- CLI commands, scripts, one-liners worth remembering
/// - `context`      -- project context: stakeholders, constraints, deadlines
/// - `decision`     -- architecture decision records (ADR)
/// - `gotcha`       -- tricky bugs, edge cases, workarounds
/// - `pattern`      -- reusable solutions, best practices
/// - `rule`         -- coding rules, lint policies, naming conventions
/// - `contract`     -- API contracts, data schemas, interface guarantees
/// - `convention`   -- team conventions, workflow norms, process agreements
/// - `template`     -- reusable file/component templates
///
/// Seed files are generated by `init` to give users a concrete starting point.
/// Each file is a valid OKF Markdown document with frontmatter and a template
/// section that the user fills in.
use crate::core::Profile;

/// The default profile used by `enjoyknowledge init`.
pub struct CodingProfile;

impl Profile for CodingProfile {
    fn name(&self) -> &'static str {
        "for-coding"
    }

    fn directories(&self) -> Vec<&str> {
        vec![
            "architecture",
            "business",
            "command",
            "context",
            "decision",
            "gotcha",
            "pattern",
            "rule",
            "contract",
            "convention",
            "template",
        ]
    }

    fn seed_files(&self) -> Vec<(&str, &str)> {
        vec![
            ("architecture/overview.md", SEED_ARCHITECTURE),
            ("business/business.md", SEED_BUSINESS),
            ("command/command.md", SEED_COMMANDS),
            ("context/context.md", SEED_CONTEXT),
            ("decision/000-template.md", SEED_DECISIONS),
            ("gotcha/gotcha.md", SEED_GOTCHAS),
            ("pattern/pattern.md", SEED_PATTERNS),
            ("rule/rule.md", SEED_RULES),
            ("contract/contract.md", SEED_CONTRACTS),
            ("convention/convention.md", SEED_CONVENTIONS),
            ("template/template.md", SEED_TEMPLATES),
        ]
    }

    fn agents_md_label(&self) -> &'static str {
        "coding"
    }
}

// ---------- Seed template content -------------------------------------------

const SEED_ARCHITECTURE: &str = include_str!("../fixtures/seeds/architecture.md");

const SEED_BUSINESS: &str = include_str!("../fixtures/seeds/business.md");

const SEED_COMMANDS: &str = include_str!("../fixtures/seeds/command.md");

const SEED_CONTEXT: &str = include_str!("../fixtures/seeds/context.md");

const SEED_DECISIONS: &str = include_str!("../fixtures/seeds/decision.md");

const SEED_GOTCHAS: &str = include_str!("../fixtures/seeds/gotcha.md");

const SEED_PATTERNS: &str = include_str!("../fixtures/seeds/pattern.md");

const SEED_RULES: &str = include_str!("../fixtures/seeds/rule.md");

const SEED_CONTRACTS: &str = include_str!("../fixtures/seeds/contract.md");

const SEED_CONVENTIONS: &str = include_str!("../fixtures/seeds/convention.md");

const SEED_TEMPLATES: &str = include_str!("../fixtures/seeds/template.md");
