/// `for-coding` profile -- 5 knowledge categories for general software
/// development projects.
///
/// Directories:
/// - `architecture` -- system design, module map, data flow
/// - `gotchas`      -- tricky bugs, edge cases, workarounds
/// - `patterns`     -- reusable solutions, best practices
/// - `business`     -- domain rules, compliance, billing logic
/// - `decisions`    -- architecture decision records (ADR)
///
/// Seed files are generated by `init` to give users a concrete starting point.
/// Each file is a valid OKF Markdown document with frontmatter and a template
/// section that the user fills in.
use crate::core::Profile;

/// The default profile used by `enjoyknowledge init`.
pub struct CodingProfile;

impl Profile for CodingProfile {
    fn name(&self) -> &'static str {
        "for-coding"
    }

    fn directories(&self) -> Vec<&str> {
        vec!["architecture", "gotchas", "patterns", "business", "decisions"]
    }

    fn seed_files(&self) -> Vec<(&str, &str)> {
        vec![
            ("architecture/overview.md", SEED_ARCHITECTURE),
            ("gotchas/gotchas.md", SEED_GOTCHAS),
            ("patterns/patterns.md", SEED_PATTERNS),
            ("business/business.md", SEED_BUSINESS),
            ("decisions/000-template.md", SEED_DECISIONS),
        ]
    }

    fn agents_md_label(&self) -> &'static str {
        "coding"
    }
}

// ---------- Seed template content -------------------------------------------

const SEED_ARCHITECTURE: &str = r"---
description: Project architecture overview -- system design, module map, data flow
timestamp: __TIMESTAMP__
---

# Architecture Overview

> Fill in your project's high-level architecture here.

## Module Map

- module-a/ -- description
- module-b/ -- description

## Tech Stack

| Layer    | Choice            | Why |
|----------|-------------------|-----|
| Runtime  |                   |     |
| Database |                   |     |
| Frontend |                   |     |

## Data Flow

```
[Request] -> [Handler] -> [Service] -> [Repository] -> [DB]
```

## Deployment Topology

Describe how the system is deployed (monolith, microservices, etc.):

```
```
";

const SEED_GOTCHAS: &str = r"---
description: Gotchas, tricky bugs, edge cases, and workarounds discovered during development
timestamp: __TIMESTAMP__
---

# Gotchas

> Record each gotcha as a ## section.
> Run: enjoyknowledge add gotchas/gotchas.md '## your title'

## Template: Short descriptive title
- **Instance**: What went wrong / what surprised you
- **Impact**: Which component or flow was affected
- **Workaround**: How it is handled now (even if imperfect)
- **Related**: Link to related architecture or patterns
";

const SEED_PATTERNS: &str = r"---
description: Validated patterns, conventions, and best practices for this project
timestamp: __TIMESTAMP__
---

# Patterns and Conventions

> Validated solutions that have worked well in this project.
> Each pattern is a ## section -- use enjoyknowledge add patterns/patterns.md '## ...'

## Template: Pattern name
- **When**: When to apply this pattern
- **How**: How it works, with a short code snippet if helpful
- **Why**: Rationale -- why this over alternatives
- **Anti-pattern**: When NOT to use it (if applicable)
";

const SEED_BUSINESS: &str = r"---
description: Business rules, domain logic, calculation formulas, and compliance requirements
timestamp: __TIMESTAMP__
---

# Business Rules

> Domain-specific rules that code must enforce.
> AI tools should check these before implementing related features.

## Template: Rule name
- **Rule**: What the rule says, in plain language
- **Scope**: Which features / endpoints / user roles are affected
- **Code location**: Where this rule is enforced (file paths or module names)
- **Test**: How to verify compliance
";

const SEED_DECISIONS: &str = r"---
description: Architecture Decision Records (ADR) -- key technical decisions and their rationale
timestamp: __TIMESTAMP__
---

# Architecture Decisions

> ADR format: title, status, context, decision, consequences.
> Number sequentially: 001-topic.md, 002-topic.md, ...

## 000 -- Use ADRs
- **Status**: Accepted
- **Context**: We need to track why key technical decisions were made.
- **Decision**: Use lightweight ADRs in decisions/.
- **Consequences**: Every significant architectural choice must be documented.
";
