use crate::core::Profile;
use crate::kinds;
/// Directory skeleton generation.
use crate::EK_DIR;
use std::fmt::Write;
use std::path::Path;

/// Canonical directory name for the stage (AI task staging area).
pub const STAGE_DIR: &str = ".enjoyknowledge_stage";

/// v0.4.8: Skills directory inside .enjoyknowledge/ for workflow skill files.
pub const SKILLS_DIR: &str = "skills";

/// Default stage-directory specification — embedded at compile-time.
const STAGE_DEFAULTS_MD_DEFAULT: &str = include_str!("../fixtures/stage-defaults.md");

/// Generate the `.enjoyknowledge/` skeleton and `knowledge-tasks/` under `project_root`.
///
/// The skeleton shape is determined by `profile.directories()` and
/// `profile.seed_files()`, so different contexts (coding, design, research, …)
/// produce different directory trees.
pub fn generate_skeleton(project_root: &Path, profile: &dyn Profile) -> anyhow::Result<()> {
    let ek = project_root.join(EK_DIR);
    std::fs::create_dir_all(&ek)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    for dir in profile.directories() {
        std::fs::create_dir_all(ek.join(dir))?;
    }

    // Write seed files (only if they don't already exist)
    for (rel_path, content) in profile.seed_files() {
        let full = ek.join(rel_path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent)?;
        }
        if !full.exists() {
            let resolved = content.replace("__TIMESTAMP__", &today);
            std::fs::write(&full, resolved)?;
        }
    }

    // v0.4.3: Write _meta/kinds.md (kind registry seed)
    let meta_dir = ek.join("_meta");
    std::fs::create_dir_all(&meta_dir)?;
    let kinds_md_path = meta_dir.join("kinds.md");
    if !kinds_md_path.exists() {
        std::fs::write(&kinds_md_path, kinds::init_default_kinds())?;
    }

    // v0.4.5: Create kind directories from user kinds.md (runtime-read, not compile-time)
    let kinds = kinds::all_from_file(&kinds_md_path).unwrap_or_else(|_| kinds::all().to_vec());
    for k in &kinds {
        let dir = ek.join(kinds::dir_for(&k.name));
        std::fs::create_dir_all(&dir)?;
    }

    // knowledge-tasks/ at project root level
    std::fs::create_dir_all(project_root.join("knowledge-tasks"))?;

    // Generate index.md (OKF table of contents)
    let index_path = ek.join("index.md");
    if !index_path.exists() {
        std::fs::write(
            &index_path,
            format!("---\ndescription: Knowledge base index — auto-generated directory of all knowledge files\ntimestamp: {today}\n---\n\n# Knowledge Index\n\n> Auto-generated by enjoyknowledge. Lists all knowledge files.\n"),
        )?;
    }

    Ok(())
}

/// Generate AGENTS.md with the knowledge summary block.
pub fn generate_agents_md(
    project_root: &Path,
    ai_tool: Option<&str>,
    profile: &dyn Profile,
) -> anyhow::Result<()> {
    let content = generate_agents_md_content(ai_tool, profile);
    std::fs::write(project_root.join("AGENTS.md"), content)?;
    Ok(())
}

/// Sync the knowledge summary block in AGENTS.md after a knowledge change (add, fix, etc.).
///
/// This reads the current state via `KnowledgeSource::list_entries` and replaces
/// the content between `<!-- enjoyknowledge_LS_START -->` and
/// `<!-- enjoyknowledge_LS_END -->` in the project root's AGENTS.md.
pub fn sync_agents_md_summary(
    project_root: &Path,
    source: &dyn crate::knowledge::KnowledgeSource,
) -> anyhow::Result<()> {
    let agents_path = project_root.join("AGENTS.md");
    if !agents_path.exists() {
        return Ok(());
    }

    let entries = source.list_entries(None, false)?;
    let summary = format_ls_summary(&entries);

    let content = std::fs::read_to_string(&agents_path)?;
    let start_marker = "<!-- enjoyknowledge_LS_START -->";
    let end_marker = "<!-- enjoyknowledge_LS_END -->";

    let Some(start_pos) = content.find(start_marker) else { return Ok(()) };
    let Some(end_pos) = content.find(end_marker) else { return Ok(()) };

    let new_content = format!(
        "{}{start_marker}\n{summary}\n{end_marker}{}",
        &content[..start_pos],
        &content[end_pos + end_marker.len()..]
    );

    std::fs::write(&agents_path, new_content)?;
    Ok(())
}

/// Render knowledge entries as a plain-text summary block for AGENTS.md.
fn format_ls_summary(entries: &[crate::knowledge::KnowledgeEntry]) -> String {
    let mut out = String::new();
    for entry in entries {
        if entry.is_dir {
            let _ = writeln!(out, "{}/", entry.path);
        } else if let Some(desc) = &entry.description {
            let _ = writeln!(out, "  {} → {}", entry.path, desc);
        } else {
            let _ = writeln!(out, "  {}", entry.path);
        }
    }
    out.trim_end().to_string()
}

/// Return AGENTS.md content as a String (used by the template system).
pub fn generate_agents_md_content(ai_tool: Option<&str>, profile: &dyn Profile) -> String {
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let summary_placeholder = r"<!-- enjoyknowledge_LS_START -->
<!-- Run `enjoyknowledge ls` to populate the knowledge summary. -->
<!-- enjoyknowledge_LS_END -->";

    let label = profile.agents_md_label();
    let tool_label = ai_tool.unwrap_or("AGENTS.md");

    format!(
        r#"# AGENTS.md

This project uses [enjoyknowledge](https://enjoyknowledge.dev) to manage shared context for AI coding tools.

## Knowledge Overview

{summary_placeholder}

Above is the current knowledge base contents. Before starting any coding task, check here to see if relevant knowledge exists.

## Commands

| Command | Why |
|---|---|
| `enjoyknowledge ls` | List files with descriptions — know what exists without opening files |
| `enjoyknowledge grep <pattern>` | Search inside `##` sections, not raw line numbers |
| `enjoyknowledge cat <path>` | Read a knowledge file (path auto-prefixed with `.enjoyknowledge/`) |
| `enjoyknowledge add <path> "<content>"` | Record a new entry (auto-generates OKF frontmatter) |
| `enjoyknowledge tree` | Recursive directory tree with descriptions |
| `enjoyknowledge doctor` | Health check (5 checks) |
| `enjoyknowledge fix` | Auto-fix common issues |

---
*Generated by enjoyknowledge init (--ai {tool_label}) [{label}] on {today}*
"#
    )
}

// ════════════════════════════════════════════════════════════════════════════
// v0.4: Stage generation — .enjoyknowledge_stage/ + 2 AGENTS.md + 8 templates
// ════════════════════════════════════════════════════════════════════════════

/// Generate the `.enjoyknowledge_stage/` directory tree and 8 template files.
///
/// v0.4.4: Reads `_meta/stage-defaults.md` (user or default) to determine
/// which directories to create. Falls back to v0.4.1 hardcoded defaults if
/// parsing fails.
pub fn generate_stage_skeleton(project_root: &Path) -> anyhow::Result<()> {
    let stage = project_root.join(STAGE_DIR);

    // v0.4.4: Read stage-defaults.md to determine directories.
    // Priority: user-edited copy > embedded default.
    let defaults_md_path = stage.join("_meta").join("stage-defaults.md");
    let defaults_md = if defaults_md_path.exists() {
        std::fs::read_to_string(&defaults_md_path).unwrap_or_default()
    } else {
        STAGE_DEFAULTS_MD_DEFAULT.to_string()
    };
    let dirs = parse_stage_defaults(&defaults_md);

    // Create directories from parsed stage-defaults.md
    for dir in &dirs {
        std::fs::create_dir_all(stage.join(dir))?;
    }
    // Always ensure .archive/tasks exists (backward compat)
    if !dirs.iter().any(|d| d == ".archive/tasks") {
        std::fs::create_dir_all(stage.join(".archive").join("tasks"))?;
    }

    // 8 template files under tasks/_template/
    let template_dir = stage.join("tasks").join("_template");
    std::fs::create_dir_all(&template_dir)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let templates: &[(&str, &str)] = &[
        ("summary.md", STAGE_TEMPLATE_SUMMARY),
        ("requirements.md", STAGE_TEMPLATE_REQUIREMENTS),
        ("design.md", STAGE_TEMPLATE_DESIGN),
        ("plan.md", STAGE_TEMPLATE_PLAN),
        ("changes.md", STAGE_TEMPLATE_CHANGES),
        ("tests.md", STAGE_TEMPLATE_TESTS),
        ("delivery.md", STAGE_TEMPLATE_DELIVERY),
        ("review.md", STAGE_TEMPLATE_REVIEW),
    ];

    for (rel_path, content) in templates {
        let full = template_dir.join(rel_path);
        if !full.exists() {
            let resolved = content.replace("__TIMESTAMP__", &today);
            std::fs::write(&full, resolved)?;
        }
    }

    Ok(())
}

/// Parse the Default Directories table from `stage-defaults.md`.
/// Returns directory paths relative to `.enjoyknowledge_stage/`.
fn parse_stage_defaults(md: &str) -> Vec<String> {
    let mut dirs: Vec<String> = Vec::new();
    let mut in_table = false;

    for line in md.lines() {
        let trimmed = line.trim();
        // Detect table header
        if trimmed.starts_with("| name ") && trimmed.contains("| purpose ") {
            in_table = true;
            continue;
        }
        if !in_table {
            continue;
        }
        // Stop at end of table
        if !trimmed.starts_with('|') {
            break;
        }
        // Skip separator line
        if trimmed.contains("---") {
            continue;
        }
        // Parse data row: | `name` | purpose | files |
        let cells: Vec<&str> =
            trimmed.split('|').map(str::trim).filter(|c| !c.is_empty()).collect();
        if cells.is_empty() {
            continue;
        }
        // Strip backticks from name
        let name = cells[0].trim_matches('`');
        dirs.push(name.to_string());
    }

    if dirs.is_empty() {
        // Fallback to v0.4.1 defaults
        dirs.extend(["tasks", "drafts", ".archive"].iter().map(std::string::ToString::to_string));
    }

    dirs
}

/// Copy the default `stage-defaults.md` to `.enjoyknowledge_stage/_meta/`.
/// Does NOT overwrite if the file already exists (user-owned).
pub fn generate_stage_defaults_md(project_root: &Path) -> anyhow::Result<()> {
    let meta_dir = project_root.join(STAGE_DIR).join("_meta");
    std::fs::create_dir_all(&meta_dir)?;

    let path = meta_dir.join("stage-defaults.md");
    if !path.exists() {
        std::fs::write(&path, STAGE_DEFAULTS_MD_DEFAULT)?;
    }
    Ok(())
}

/// Generate `.enjoyknowledge/AGENTS.md` — the KB index that AI tools read.
/// v0.4.6: Does NOT overwrite if the file already exists (user-owned).
pub fn generate_ek_agents_md(project_root: &Path) -> anyhow::Result<()> {
    let ek = project_root.join(EK_DIR);
    std::fs::create_dir_all(&ek)?;

    let path = ek.join("AGENTS.md");
    if !path.exists() {
        std::fs::write(&path, EK_AGENTS_MD_CONTENT)?;
    }
    Ok(())
}

/// Generate `.enjoyknowledge_stage/AGENTS.md` — the stage writing spec for AI tools.
///
/// v0.4.4: Does NOT overwrite if the file already exists (user-owned).
pub fn generate_stage_agents_md(project_root: &Path) -> anyhow::Result<()> {
    let stage = project_root.join(STAGE_DIR);
    std::fs::create_dir_all(&stage)?;

    let path = stage.join("AGENTS.md");
    if !path.exists() {
        std::fs::write(&path, STAGE_AGENTS_MD_CONTENT)?;
    }
    Ok(())
}

/// Generate `.enjoyknowledge/skills/` — 4 workflow skills + 1 README index.
///
/// v0.4.8: Does NOT overwrite existing skill files (user-owned).
pub fn generate_skills_skeleton(project_root: &Path) -> anyhow::Result<()> {
    let skills_dir = project_root.join(EK_DIR).join(SKILLS_DIR);
    std::fs::create_dir_all(&skills_dir)?;

    let files: &[(&str, &str)] = &[
        ("coding.md", SKILLS_CODING_MD_CONTENT),
        ("research.md", SKILLS_RESEARCH_MD_CONTENT),
        ("review.md", SKILLS_REVIEW_MD_CONTENT),
        ("design.md", SKILLS_DESIGN_MD_CONTENT),
        ("README.md", SKILLS_README_MD_CONTENT),
    ];

    for (name, content) in files {
        let path = skills_dir.join(name);
        if !path.exists() {
            std::fs::write(&path, *content)?;
        }
    }

    Ok(())
}

/// Update `.gitignore` to exclude stage working files.
pub fn update_gitignore(project_root: &Path) -> anyhow::Result<()> {
    let gi = project_root.join(".gitignore");
    let rules =
        "\n# enjoyknowledge stage (v0.4+)\n.enjoyknowledge_stage/tasks/*/changes.md\n.session/\n";

    if gi.exists() {
        let existing = std::fs::read_to_string(&gi)?;
        if !existing.contains(".enjoyknowledge_stage/tasks/*/changes.md") {
            std::fs::write(&gi, format!("{existing}{rules}"))?;
        }
    }

    Ok(())
}

// ════════════════════════════════════════════════════════════════════════════
// v0.4.8: Skills workflow files (4 flow + 1 index)
// ════════════════════════════════════════════════════════════════════════════

const SKILLS_CODING_MD_CONTENT: &str = include_str!("../fixtures/skills/coding.md");

const SKILLS_RESEARCH_MD_CONTENT: &str = include_str!("../fixtures/skills/research.md");

const SKILLS_REVIEW_MD_CONTENT: &str = include_str!("../fixtures/skills/review.md");

const SKILLS_DESIGN_MD_CONTENT: &str = include_str!("../fixtures/skills/design.md");

const SKILLS_README_MD_CONTENT: &str = include_str!("../fixtures/skills/README.md");

const EK_AGENTS_MD_CONTENT: &str = include_str!("../fixtures/agents/ek.md");

const STAGE_AGENTS_MD_CONTENT: &str = include_str!("../fixtures/agents/stage.md");

// ════════════════════════════════════════════════════════════════════════════
// v0.4: AGENTS.md content + 8 stage template content
// ════════════════════════════════════════════════════════════════════════════

const STAGE_TEMPLATE_SUMMARY: &str = r"---
task: <task-id>
phase: cross-phase
status: draft
created: __TIMESTAMP__
---

# Task Summary: <task-id>

> Two-section format: start (task assigned) + stage log (append-only).

## Start

- **Assigned**: __TIMESTAMP__
- **Source**: <issue/PR/human request>
- **Goal**: One sentence describing the task outcome

## Stage Log

| Timestamp | Phase | Event |
|-----------|-------|-------|
| __TIMESTAMP__ | P1 | Task created |
";

const STAGE_TEMPLATE_REQUIREMENTS: &str = r"---
task: <task-id>
phase: P1
status: draft
created: __TIMESTAMP__
---

# Requirements: <task-id>

> EARS format: Event → Action → Response → State.

## Functional Requirements

### FR-1: <title>
- **Event**: When <trigger>
- **Action**: The system shall <action>
- **Response**: The user sees <response>

## Acceptance Criteria

- [ ] AC-1: <criterion>
- [ ] AC-2: <criterion>

## Scope & Boundaries

- **In scope**: <what is included>
- **Out of scope**: <what is not included>

## Clarifications

| # | Question | Answer | Answered by |
|---|----------|--------|-------------|
| 1 |          |        |             |
";

const STAGE_TEMPLATE_DESIGN: &str = r"---
task: <task-id>
phase: P2
status: draft
created: __TIMESTAMP__
---

# Design: <task-id>

> Technical approach, trade-offs, and architecture decisions.

## Approach

<Paragraph describing the chosen approach>

## Trade-offs

| Option | Pros | Cons | Chosen? |
|--------|------|------|---------|
|        |      |      | ✓       |

## Architecture

```
<diagram or description>
```

## Files to Change

| File | Change | Reason |
|------|--------|--------|
|      |        |        |

## Decisions

| # | Decision | Rationale |
|---|----------|-----------|
| 1 |          |           |
";

const STAGE_TEMPLATE_PLAN: &str = r"---
task: <task-id>
phase: P2b
status: draft
created: __TIMESTAMP__
---

# Plan: <task-id>

> Subtask breakdown and execution order.

## Subtasks

| # | Subtask | Estimate | Depends on | Status |
|---|---------|----------|------------|--------|
| 1 |         |          | —          | ⬜     |
| 2 |         |          | 1          | ⬜     |

## Execution Order

```
1. <first subtask>
2. <second subtask>
```

## Risk Register

| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
|      |           |        |            |
";

const STAGE_TEMPLATE_CHANGES: &str = r"---
task: <task-id>
phase: P3
status: draft
created: __TIMESTAMP__
---

# Changes: <task-id>

> **APPEND-ONLY**. One line per file edit.
> **Gitignored** — audit trail, not version-controlled.

| # | Timestamp | File | Change |
|---|-----------|------|--------|
| 1 | __TIMESTAMP__ | — | Task started |
";

const STAGE_TEMPLATE_TESTS: &str = r"---
task: <task-id>
phase: P4
status: draft
created: __TIMESTAMP__
---

# Tests: <task-id>

> Coverage matrix + results + risks.

## Coverage Matrix

| Test | Type | Covers | Status |
|------|------|--------|--------|
|      | unit |        | ⬜     |

## Test Results

```
<output from cargo test / test runner>
```

## Risks & Gaps

- **Risk**: <what could still break>
- **Gap**: <what is not tested and why>
";

const STAGE_TEMPLATE_DELIVERY: &str = r"---
task: <task-id>
phase: P5
status: draft
created: __TIMESTAMP__
---

# Delivery: <task-id>

> Final commit + PR + KB promote decisions.

## Commits

| # | Hash | Message |
|---|------|---------|
| 1 |      |         |

## PR

- **Title**:
- **Description**:

## KB Promote

| Knowledge | Kind | Promote? | File |
|-----------|------|----------|------|
|           |      | ⬜       |      |

## Post-Delivery

- [ ] Tests passing
- [ ] Docs updated
- [ ] KB promoted
- [ ] Task archived
";

const STAGE_TEMPLATE_REVIEW: &str = r"---
task: <task-id>
phase: cross-phase
status: draft
created: __TIMESTAMP__
---

# Review Checklist: <task-id>

> **AI pre-fills [ ] — humans tick [x].** AI must never use [x].

## P1: Requirements

- [ ] Requirements are complete and accurate
- [ ] Acceptance criteria are testable
- [ ] Scope boundaries are clear
- [ ] All clarifications resolved

**Gate 1**: ⬜ Approved — AI may proceed to P2 design

---

## P2: Design

- [ ] Approach is sound
- [ ] Trade-offs are documented and acceptable
- [ ] Architecture diagram is clear
- [ ] Files to change are identified

**Gate 2**: ⬜ Approved — AI may proceed to P3 coding

---

## P4: Testing

- [ ] Coverage matrix is complete
- [ ] All tests pass
- [ ] Edge cases covered
- [ ] Risks documented

---

## P5: Delivery

- [ ] All commits have clear messages
- [ ] PR is ready for review
- [ ] KB promotions identified
- [ ] Task can be archived

**Gate 3**: ⬜ Approved — Deliver + Archive task

---

## Final Sign-off

- [ ] All 3 gates approved
- [ ] Task complete
- [ ] Archive ready
";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_stage_skeleton_creates_structure() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        generate_stage_skeleton(root).unwrap();

        assert!(root.join(".enjoyknowledge_stage/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/drafts").exists());
        assert!(root.join(".enjoyknowledge_stage/.archive/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/tasks/_template").exists());
    }

    #[test]
    fn generate_stage_skeleton_creates_8_templates() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        generate_stage_skeleton(root).unwrap();

        let template_dir = root.join(".enjoyknowledge_stage/tasks/_template");
        for name in &[
            "summary.md",
            "requirements.md",
            "design.md",
            "plan.md",
            "changes.md",
            "tests.md",
            "delivery.md",
            "review.md",
        ] {
            assert!(template_dir.join(name).exists(), "missing template: {name}");
        }
    }

    #[test]
    fn generate_stage_skeleton_templates_idempotent() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        // First run creates templates
        generate_stage_skeleton(root).unwrap();
        let first_size =
            std::fs::read_to_string(root.join(".enjoyknowledge_stage/tasks/_template/summary.md"))
                .unwrap()
                .len();

        // Second run should not overwrite existing templates
        generate_stage_skeleton(root).unwrap();
        let second_size =
            std::fs::read_to_string(root.join(".enjoyknowledge_stage/tasks/_template/summary.md"))
                .unwrap()
                .len();

        assert_eq!(first_size, second_size);
    }

    #[test]
    fn generate_ek_agents_md_produces_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge")).unwrap();

        generate_ek_agents_md(root).unwrap();

        let content = std::fs::read_to_string(root.join(".enjoyknowledge/AGENTS.md")).unwrap();
        assert!(content.contains("enjoyknowledge 知识库"));
        assert!(content.contains("architecture/"));
        assert!(content.contains("gotcha/"));
        assert!(content.contains("rule/"));
        assert!(content.contains("读写原则"));
    }

    #[test]
    fn generate_ek_agents_md_does_not_overwrite() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        let ek = root.join(".enjoyknowledge");
        std::fs::create_dir_all(&ek).unwrap();
        let agents_path = ek.join("AGENTS.md");
        std::fs::write(&agents_path, "USER-MARKER-12345\n").unwrap();
        generate_ek_agents_md(root).unwrap();
        let content = std::fs::read_to_string(&agents_path).unwrap();
        assert!(content.contains("USER-MARKER-12345"), "user marker should be preserved");
        assert!(!content.contains("enjoyknowledge-kb"), "default should NOT overwrite");
    }

    #[test]
    fn generate_stage_agents_md_produces_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge_stage")).unwrap();

        generate_stage_agents_md(root).unwrap();

        let content =
            std::fs::read_to_string(root.join(".enjoyknowledge_stage/AGENTS.md")).unwrap();
        assert!(content.contains("enjoyknowledge 任务执行"));
        assert!(content.contains("任务执行流程"));
        assert!(content.contains("drafts/"));
        assert!(content.contains("ek promote"));
    }

    #[test]
    fn generate_stage_agents_md_does_not_overwrite() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge_stage")).unwrap();

        // Write user-customized content
        let user_content = "# My Custom Stage Rules\n\nThis is user-edited.";
        std::fs::write(root.join(".enjoyknowledge_stage/AGENTS.md"), user_content).unwrap();

        // Call generate — should not overwrite
        generate_stage_agents_md(root).unwrap();

        let actual = std::fs::read_to_string(root.join(".enjoyknowledge_stage/AGENTS.md")).unwrap();
        assert_eq!(actual, user_content);
    }

    #[test]
    fn generate_stage_defaults_md_produces_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        generate_stage_defaults_md(root).unwrap();

        let path = root.join(".enjoyknowledge_stage/_meta/stage-defaults.md");
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("Stage Default Directories"));
        assert!(content.contains("| name | purpose | files |"));
    }

    #[test]
    fn generate_stage_defaults_md_does_not_overwrite() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge_stage/_meta")).unwrap();

        let user_content = "# My custom stage defaults\n\nI changed this.";
        std::fs::write(root.join(".enjoyknowledge_stage/_meta/stage-defaults.md"), user_content)
            .unwrap();

        generate_stage_defaults_md(root).unwrap();

        let actual =
            std::fs::read_to_string(root.join(".enjoyknowledge_stage/_meta/stage-defaults.md"))
                .unwrap();
        assert_eq!(actual, user_content);
    }

    #[test]
    fn parse_stage_defaults_parses_default_table() {
        let dirs = parse_stage_defaults(STAGE_DEFAULTS_MD_DEFAULT);
        assert!(dirs.contains(&"tasks".to_string()));
        assert!(dirs.contains(&"drafts".to_string()));
        assert!(dirs.contains(&".archive".to_string()));
    }

    #[test]
    fn parse_stage_defaults_fallback_on_empty() {
        let dirs = parse_stage_defaults("");
        assert!(dirs.contains(&"tasks".to_string()));
        assert!(dirs.contains(&"drafts".to_string()));
        assert!(dirs.contains(&".archive".to_string()));
    }

    #[test]
    fn generate_stage_skeleton_reads_defaults_md() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        // First write a custom stage-defaults.md with an extra dir
        let meta_dir = root.join(".enjoyknowledge_stage/_meta");
        std::fs::create_dir_all(&meta_dir).unwrap();
        let custom_defaults = "# Stage Default Directories\n\n## Default Directories\n\n| name | purpose | files |\n|------|---------|-------|\n| `tasks` | Active task records | summary/requirements |\n| `drafts` | Knowledge drafts | (user writes freely) |\n| `.archive` | Completed/archived tasks | (auto) |\n| `experiments` | Experiment records | (user writes freely) |\n";
        std::fs::write(meta_dir.join("stage-defaults.md"), custom_defaults).unwrap();

        generate_stage_skeleton(root).unwrap();

        assert!(root.join(".enjoyknowledge_stage/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/drafts").exists());
        assert!(root.join(".enjoyknowledge_stage/.archive/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/experiments").exists());
    }

    #[test]
    fn update_gitignore_adds_rules() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::write(root.join(".gitignore"), "target/\n").unwrap();

        update_gitignore(root).unwrap();

        let content = std::fs::read_to_string(root.join(".gitignore")).unwrap();
        assert!(content.contains(".enjoyknowledge_stage/tasks/*/changes.md"));
        assert!(content.contains(".session/"));
    }

    #[test]
    fn update_gitignore_no_existing_does_not_error() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        update_gitignore(root).unwrap();

        // No .gitignore file should be created if it doesn't exist
        assert!(!root.join(".gitignore").exists());
    }

    #[test]
    fn update_gitignore_idempotent() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::write(root.join(".gitignore"), "target/\n").unwrap();

        update_gitignore(root).unwrap();
        let first = std::fs::read_to_string(root.join(".gitignore")).unwrap();

        update_gitignore(root).unwrap();
        let second = std::fs::read_to_string(root.join(".gitignore")).unwrap();

        assert_eq!(first, second);
    }

    // ════════════════════════════════════════════════════════════════════════════
    // v0.4.9: Extraction verification tests
    // ════════════════════════════════════════════════════════════════════════════

    #[test]
    fn v0_4_9_md_content_uses_include_str() {
        // Verify all 7 MD_CONTENT constants are non-empty (compile-time embedded via include_str!)
        assert!(!SKILLS_CODING_MD_CONTENT.is_empty());
        assert!(SKILLS_CODING_MD_CONTENT.contains("enjoyknowledge-flow-coding"));
        assert!(SKILLS_CODING_MD_CONTENT.contains("编码工作流"));

        assert!(!SKILLS_RESEARCH_MD_CONTENT.is_empty());
        assert!(SKILLS_RESEARCH_MD_CONTENT.contains("enjoyknowledge-flow-research"));
        assert!(SKILLS_RESEARCH_MD_CONTENT.contains("调研工作流"));

        assert!(!SKILLS_REVIEW_MD_CONTENT.is_empty());
        assert!(SKILLS_REVIEW_MD_CONTENT.contains("enjoyknowledge-flow-review"));
        assert!(SKILLS_REVIEW_MD_CONTENT.contains("复盘工作流"));

        assert!(!SKILLS_DESIGN_MD_CONTENT.is_empty());
        assert!(SKILLS_DESIGN_MD_CONTENT.contains("enjoyknowledge-flow-design"));
        assert!(SKILLS_DESIGN_MD_CONTENT.contains("设计工作流"));

        assert!(!SKILLS_README_MD_CONTENT.is_empty());
        assert!(SKILLS_README_MD_CONTENT.contains("enjoyknowledge-skills-index"));
        assert!(SKILLS_README_MD_CONTENT.contains("4 个工作流"));

        assert!(!EK_AGENTS_MD_CONTENT.is_empty());
        assert!(EK_AGENTS_MD_CONTENT.contains("enjoyknowledge-kb"));
        assert!(EK_AGENTS_MD_CONTENT.contains("知识库根"));

        assert!(!STAGE_AGENTS_MD_CONTENT.is_empty());
        assert!(STAGE_AGENTS_MD_CONTENT.contains("enjoyknowledge-stage"));
        assert!(STAGE_AGENTS_MD_CONTENT.contains("任务执行区"));
    }

    #[test]
    fn v0_4_9_user_can_modify_md_content_via_fixture() {
        // Verify all 7 fixture files exist and are readable
        // (include_str! loads at compile time, so these file reads mirror what the constants contain)
        let skills_dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/fixtures/skills");
        let agents_dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/fixtures/agents");

        let coding = std::fs::read_to_string(skills_dir.join("coding.md")).unwrap();
        assert!(coding.contains("enjoyknowledge-flow-coding"));
        assert_eq!(coding, SKILLS_CODING_MD_CONTENT);

        let research = std::fs::read_to_string(skills_dir.join("research.md")).unwrap();
        assert!(research.contains("enjoyknowledge-flow-research"));
        assert_eq!(research, SKILLS_RESEARCH_MD_CONTENT);

        let review = std::fs::read_to_string(skills_dir.join("review.md")).unwrap();
        assert!(review.contains("enjoyknowledge-flow-review"));
        assert_eq!(review, SKILLS_REVIEW_MD_CONTENT);

        let design = std::fs::read_to_string(skills_dir.join("design.md")).unwrap();
        assert!(design.contains("enjoyknowledge-flow-design"));
        assert_eq!(design, SKILLS_DESIGN_MD_CONTENT);

        let readme = std::fs::read_to_string(skills_dir.join("README.md")).unwrap();
        assert!(readme.contains("enjoyknowledge-skills-index"));
        assert_eq!(readme, SKILLS_README_MD_CONTENT);

        let stage_agents = std::fs::read_to_string(agents_dir.join("stage.md")).unwrap();
        assert!(stage_agents.contains("enjoyknowledge-stage"));
        assert_eq!(stage_agents, STAGE_AGENTS_MD_CONTENT);

        let ek_agents = std::fs::read_to_string(agents_dir.join("ek.md")).unwrap();
        assert!(ek_agents.contains("enjoyknowledge-kb"));
        assert_eq!(ek_agents, EK_AGENTS_MD_CONTENT);
    }
}
