use crate::core::Profile;
/// Directory skeleton generation.
use crate::EK_DIR;
use std::fmt::Write;
use std::path::Path;

/// Canonical directory name for the stage (AI task staging area).
pub const STAGE_DIR: &str = ".enjoyknowledge_stage";

/// Generate the `.enjoyknowledge/` skeleton and `knowledge-tasks/` under `project_root`.
///
/// The skeleton shape is determined by `profile.directories()` and
/// `profile.seed_files()`, so different contexts (coding, design, research, …)
/// produce different directory trees.
pub fn generate_skeleton(project_root: &Path, profile: &dyn Profile) -> anyhow::Result<()> {
    let ek = project_root.join(EK_DIR);
    std::fs::create_dir_all(&ek)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    for dir in profile.directories() {
        std::fs::create_dir_all(ek.join(dir))?;
    }

    // Write seed files (only if they don't already exist)
    for (rel_path, content) in profile.seed_files() {
        let full = ek.join(rel_path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent)?;
        }
        if !full.exists() {
            let resolved = content.replace("__TIMESTAMP__", &today);
            std::fs::write(&full, resolved)?;
        }
    }

    // knowledge-tasks/ at project root level
    std::fs::create_dir_all(project_root.join("knowledge-tasks"))?;

    // Generate index.md (OKF table of contents)
    let index_path = ek.join("index.md");
    if !index_path.exists() {
        std::fs::write(
            &index_path,
            format!("---\ndescription: Knowledge base index — auto-generated directory of all knowledge files\ntimestamp: {today}\n---\n\n# Knowledge Index\n\n> Auto-generated by enjoyknowledge. Lists all knowledge files.\n"),
        )?;
    }

    Ok(())
}

/// Generate AGENTS.md with the knowledge summary block.
pub fn generate_agents_md(
    project_root: &Path,
    ai_tool: Option<&str>,
    profile: &dyn Profile,
) -> anyhow::Result<()> {
    let content = generate_agents_md_content(ai_tool, profile);
    std::fs::write(project_root.join("AGENTS.md"), content)?;
    Ok(())
}

/// Sync the knowledge summary block in AGENTS.md after a knowledge change (add, fix, etc.).
///
/// This reads the current state via `KnowledgeSource::list_entries` and replaces
/// the content between `<!-- enjoyknowledge_LS_START -->` and
/// `<!-- enjoyknowledge_LS_END -->` in the project root's AGENTS.md.
pub fn sync_agents_md_summary(
    project_root: &Path,
    source: &dyn crate::knowledge::KnowledgeSource,
) -> anyhow::Result<()> {
    let agents_path = project_root.join("AGENTS.md");
    if !agents_path.exists() {
        return Ok(());
    }

    let entries = source.list_entries(None, false)?;
    let summary = format_ls_summary(&entries);

    let content = std::fs::read_to_string(&agents_path)?;
    let start_marker = "<!-- enjoyknowledge_LS_START -->";
    let end_marker = "<!-- enjoyknowledge_LS_END -->";

    let Some(start_pos) = content.find(start_marker) else { return Ok(()) };
    let Some(end_pos) = content.find(end_marker) else { return Ok(()) };

    let new_content = format!(
        "{}{start_marker}\n{summary}\n{end_marker}{}",
        &content[..start_pos],
        &content[end_pos + end_marker.len()..]
    );

    std::fs::write(&agents_path, new_content)?;
    Ok(())
}

/// Render knowledge entries as a plain-text summary block for AGENTS.md.
fn format_ls_summary(entries: &[crate::knowledge::KnowledgeEntry]) -> String {
    let mut out = String::new();
    for entry in entries {
        if entry.is_dir {
            let _ = writeln!(out, "{}/", entry.path);
        } else if let Some(desc) = &entry.description {
            let _ = writeln!(out, "  {} → {}", entry.path, desc);
        } else {
            let _ = writeln!(out, "  {}", entry.path);
        }
    }
    out.trim_end().to_string()
}

/// Return AGENTS.md content as a String (used by the template system).
pub fn generate_agents_md_content(ai_tool: Option<&str>, profile: &dyn Profile) -> String {
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let summary_placeholder = r"<!-- enjoyknowledge_LS_START -->
<!-- Run `enjoyknowledge ls` to populate the knowledge summary. -->
<!-- enjoyknowledge_LS_END -->";

    let label = profile.agents_md_label();
    let tool_label = ai_tool.unwrap_or("AGENTS.md");

    format!(
        r#"# AGENTS.md

This project uses [enjoyknowledge](https://enjoyknowledge.dev) to manage shared context for AI coding tools.

## Knowledge Overview

{summary_placeholder}

Above is the current knowledge base contents. Before starting any coding task, check here to see if relevant knowledge exists.

## Commands

| Command | Why |
|---|---|
| `enjoyknowledge ls` | List files with descriptions — know what exists without opening files |
| `enjoyknowledge grep <pattern>` | Search inside `##` sections, not raw line numbers |
| `enjoyknowledge cat <path>` | Read a knowledge file (path auto-prefixed with `.enjoyknowledge/`) |
| `enjoyknowledge add <path> "<content>"` | Record a new entry (auto-generates OKF frontmatter) |
| `enjoyknowledge tree` | Recursive directory tree with descriptions |
| `enjoyknowledge doctor` | Health check (5 checks) |
| `enjoyknowledge fix` | Auto-fix common issues |

---
*Generated by enjoyknowledge init (--ai {tool_label}) [{label}] on {today}*
"#
    )
}

// ════════════════════════════════════════════════════════════════════════════
// v0.4: Stage generation — .enjoyknowledge_stage/ + 2 AGENTS.md + 8 templates
// ════════════════════════════════════════════════════════════════════════════

/// Generate the `.enjoyknowledge_stage/` directory tree and 8 template files.
pub fn generate_stage_skeleton(project_root: &Path) -> anyhow::Result<()> {
    let stage = project_root.join(STAGE_DIR);

    // Top-level directories
    std::fs::create_dir_all(stage.join("tasks"))?;
    std::fs::create_dir_all(stage.join("drafts"))?;
    std::fs::create_dir_all(stage.join(".archive").join("tasks"))?;

    // 8 template files under tasks/_template/
    let template_dir = stage.join("tasks").join("_template");
    std::fs::create_dir_all(&template_dir)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let templates: &[(&str, &str)] = &[
        ("summary.md", STAGE_TEMPLATE_SUMMARY),
        ("requirements.md", STAGE_TEMPLATE_REQUIREMENTS),
        ("design.md", STAGE_TEMPLATE_DESIGN),
        ("plan.md", STAGE_TEMPLATE_PLAN),
        ("changes.md", STAGE_TEMPLATE_CHANGES),
        ("tests.md", STAGE_TEMPLATE_TESTS),
        ("delivery.md", STAGE_TEMPLATE_DELIVERY),
        ("review.md", STAGE_TEMPLATE_REVIEW),
    ];

    for (rel_path, content) in templates {
        let full = template_dir.join(rel_path);
        if !full.exists() {
            let resolved = content.replace("__TIMESTAMP__", &today);
            std::fs::write(&full, resolved)?;
        }
    }

    Ok(())
}

/// Generate `.enjoyknowledge/AGENTS.md` — the KB index that AI tools read.
pub fn generate_ek_agents_md(project_root: &Path) -> anyhow::Result<()> {
    let ek = project_root.join(EK_DIR);
    std::fs::create_dir_all(&ek)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();
    let content = ek_agents_md_content(&today);
    std::fs::write(ek.join("AGENTS.md"), content)?;
    Ok(())
}

/// Generate `.enjoyknowledge_stage/AGENTS.md` — the stage writing spec for AI tools.
pub fn generate_stage_agents_md(project_root: &Path) -> anyhow::Result<()> {
    let stage = project_root.join(STAGE_DIR);
    std::fs::create_dir_all(&stage)?;

    let content = STAGE_AGENTS_MD_CONTENT;
    std::fs::write(stage.join("AGENTS.md"), content)?;
    Ok(())
}

/// Update `.gitignore` to exclude stage working files.
pub fn update_gitignore(project_root: &Path) -> anyhow::Result<()> {
    let gi = project_root.join(".gitignore");
    let rules = "\n# enjoyknowledge stage (v0.4+)\n.enjoyknowledge_stage/tasks/*/changes.md\n.session/\n";

    if gi.exists() {
        let existing = std::fs::read_to_string(&gi)?;
        if !existing.contains(".enjoyknowledge_stage/tasks/*/changes.md") {
            std::fs::write(&gi, format!("{existing}{rules}"))?;
        }
    }

    Ok(())
}

// ════════════════════════════════════════════════════════════════════════════
// v0.4: AGENTS.md content + 8 stage template content
// ════════════════════════════════════════════════════════════════════════════

fn ek_agents_md_content(today: &str) -> String {
    format!(
        r"---
description: Knowledge base index and AI tool usage guide
timestamp: {today}
---

# AGENTS.md — EnjoyKnowledge KB Index

This project uses [enjoyknowledge](https://enjoyknowledge.dev) for shared AI context.
**All knowledge in `.enjoyknowledge/` is human-reviewed.** AI tools read this file at startup.

## KB Index

<!-- enjoyknowledge_KB_INDEX -->
| Kind | Directory | Description |
|------|-----------|-------------|
| architecture | `architecture/` | System design, module map, data flow |
| business | `business/` | Domain rules, compliance, billing logic |
| commands | `commands/` | CLI commands, scripts, one-liners |
| context | `context/` | Stakeholders, constraints, deadlines |
| decisions | `decisions/` | Architecture Decision Records (ADR) |
| gotchas | `gotchas/` | Tricky bugs, edge cases, workarounds |
| patterns | `patterns/` | Reusable solutions, best practices |
| rules | `rules/` | Coding rules, lint policies |
| contracts | `contracts/` | API contracts, data schemas |
| conventions | `conventions/` | Team conventions, workflow norms |
| templates | `templates/` | Reusable file/component templates |
<!-- /enjoyknowledge_KB_INDEX -->

## AI Read Rules

**On startup and before any coding task**, read:
1. This file (KB index) — know what knowledge exists
2. Select `cat` relevant files — get detailed context
3. Use `grep <pattern>` — search within knowledge sections

## AI Write Rules

**NEVER write to `.enjoyknowledge/` directly** unless the human explicitly asks:
- `ek add <path> <content>` — append a knowledge entry
- AI drafts go to `.enjoyknowledge_stage/drafts/`, promoted by human via `ek promote`

## Commands

| Command | Why |
|---------|-----|
| `ek ls` | List files with descriptions |
| `ek grep <pattern>` | Search inside `##` sections |
| `ek cat <path>` | Read a knowledge file |
| `ek add <path> <content>` | Record a new entry |
| `ek tree` | Recursive directory tree |
| `ek doctor` | Health check |
| `ek fix` | Auto-fix common issues |
| `ek promote <draft> --to <kind>` | Promote a draft to KB |
| `ek stage clean` | Clean old archived tasks |

---
*Generated by `ek init`. See `.enjoyknowledge_stage/AGENTS.md` for stage writing conventions.*
"
    )
}

const STAGE_AGENTS_MD_CONTENT: &str = r#"# AGENTS.md — EnjoyKnowledge Stage Writing Spec

This file tells AI tools **how to use `.enjoyknowledge_stage/`** during coding tasks.
Read at startup alongside `../.enjoyknowledge/AGENTS.md` and the project root `AGENTS.md`.

## Directory Layout

```
.enjoyknowledge_stage/
├── AGENTS.md           ← You are here
├── tasks/              ← Active task records
│   └── <task-id>/      ← One directory per task
│       ├── summary.md
│       ├── requirements.md
│       ├── design.md
│       ├── plan.md
│       ├── changes.md
│       ├── tests.md
│       ├── delivery.md
│       └── review.md
├── drafts/             ← Knowledge drafts (promote → KB)
└── .archive/           ← Completed/archived tasks
```

## 8-File System (5 Phases × 3 Hard Gates)

| Phase | File | Write Trigger | Hard Gate? |
|-------|------|---------------|------------|
| P1 Requirements | `requirements.md` | After reading issue + 3+ source files | **Gate 1** |
| P2 Design | `design.md` | After requirements confirmed | **Gate 2** |
| P2b Plan | `plan.md` | After design confirmed | No |
| P3 Coding | `changes.md` | After every file edit (append-only) | No |
| P4 Testing | `tests.md` | Before first test run + after each run | Soft gate |
| P5 Delivery | `delivery.md` | After all tests pass | **Gate 3** |
| — | `summary.md` | Task start + each phase complete | — |
| — | `review.md` | Each phase complete (AI pre-fills) | Human ticks |

## Writing Rules

### For ALL files
- Use EARS format for requirements (Event → Action → Response → State)
- Start each file with YAML frontmatter:
  ```yaml
  ---
  task: <task-id>
  phase: P1 | P2 | P2b | P3 | P4 | P5
  status: draft | in-progress | done
  ---
  ```

### `changes.md` — Append-only log
- **Add one line per file edit** (old → new summary)
- **NEVER rewrite** — this is an audit log
- **Gitignored** — does not go into version control

### `review.md` — AI pre-fills, human ticks
- AI fills checkboxes with `[ ]` (never `[x]`)
- **Only humans tick `[x]`**
- Each phase produces a checklist section

## Hard Gate Protocol

```
P1 requirements ──[Human Gate 1]──→ P2 design ──[Human Gate 2]──→ P3 coding
    ↓ (must approve before AI proceeds)

P3 coding → P4 testing ──(Human reviews tests.md)──→ P5 delivery
    ↓ (no hard gate — AI can proceed)

P5 delivery ──[Human Gate 3]──→ promote to KB + archive task
```

## Promote Workflow

1. AI writes knowledge drafts to `.enjoyknowledge_stage/drafts/<id>.md`
2. Human reviews + runs `ek promote <draft> --to <kind>`
3. Draft gets `[PROMOTED]` marker, stays for audit

### Draft frontmatter (kind-specific required fields)

When writing drafts in `.enjoyknowledge_stage/drafts/`, **include the kind's required frontmatter field** so the promoted KB file passes `ek doctor`:

| Kind | Required field | Example |
|------|---------------|---------|
| gotcha | `trigger` | `trigger: "user submits empty form"` |
| rule / contract / convention / template | `applies_to` | `applies_to: ["src/cli/**"]` |
| decision | `reversible` + `decided_at` | `reversible: false` + `decided_at: 2026-06-28` |

**Why?** `ek doctor` checks KB files for kind-specific required fields. Drafts without these fields will fail doctor after promote. **AI must fill these when writing drafts** — do not rely on `ek promote` to auto-fill (promote is intentionally minimal, 4-field base only).

**For other kinds** (architecture / business / context / pattern / command): no extra frontmatter needed.

---

*Generated by `ek init` v0.4. Follow this spec for all stage writes.*
"#;

const STAGE_TEMPLATE_SUMMARY: &str = r"---
task: <task-id>
phase: cross-phase
status: draft
created: __TIMESTAMP__
---

# Task Summary: <task-id>

> Two-section format: start (task assigned) + stage log (append-only).

## Start

- **Assigned**: __TIMESTAMP__
- **Source**: <issue/PR/human request>
- **Goal**: One sentence describing the task outcome

## Stage Log

| Timestamp | Phase | Event |
|-----------|-------|-------|
| __TIMESTAMP__ | P1 | Task created |
";

const STAGE_TEMPLATE_REQUIREMENTS: &str = r"---
task: <task-id>
phase: P1
status: draft
created: __TIMESTAMP__
---

# Requirements: <task-id>

> EARS format: Event → Action → Response → State.

## Functional Requirements

### FR-1: <title>
- **Event**: When <trigger>
- **Action**: The system shall <action>
- **Response**: The user sees <response>

## Acceptance Criteria

- [ ] AC-1: <criterion>
- [ ] AC-2: <criterion>

## Scope & Boundaries

- **In scope**: <what is included>
- **Out of scope**: <what is not included>

## Clarifications

| # | Question | Answer | Answered by |
|---|----------|--------|-------------|
| 1 |          |        |             |
";

const STAGE_TEMPLATE_DESIGN: &str = r"---
task: <task-id>
phase: P2
status: draft
created: __TIMESTAMP__
---

# Design: <task-id>

> Technical approach, trade-offs, and architecture decisions.

## Approach

<Paragraph describing the chosen approach>

## Trade-offs

| Option | Pros | Cons | Chosen? |
|--------|------|------|---------|
|        |      |      | ✓       |

## Architecture

```
<diagram or description>
```

## Files to Change

| File | Change | Reason |
|------|--------|--------|
|      |        |        |

## Decisions

| # | Decision | Rationale |
|---|----------|-----------|
| 1 |          |           |
";

const STAGE_TEMPLATE_PLAN: &str = r"---
task: <task-id>
phase: P2b
status: draft
created: __TIMESTAMP__
---

# Plan: <task-id>

> Subtask breakdown and execution order.

## Subtasks

| # | Subtask | Estimate | Depends on | Status |
|---|---------|----------|------------|--------|
| 1 |         |          | —          | ⬜     |
| 2 |         |          | 1          | ⬜     |

## Execution Order

```
1. <first subtask>
2. <second subtask>
```

## Risk Register

| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
|      |           |        |            |
";

const STAGE_TEMPLATE_CHANGES: &str = r"---
task: <task-id>
phase: P3
status: draft
created: __TIMESTAMP__
---

# Changes: <task-id>

> **APPEND-ONLY**. One line per file edit.
> **Gitignored** — audit trail, not version-controlled.

| # | Timestamp | File | Change |
|---|-----------|------|--------|
| 1 | __TIMESTAMP__ | — | Task started |
";

const STAGE_TEMPLATE_TESTS: &str = r"---
task: <task-id>
phase: P4
status: draft
created: __TIMESTAMP__
---

# Tests: <task-id>

> Coverage matrix + results + risks.

## Coverage Matrix

| Test | Type | Covers | Status |
|------|------|--------|--------|
|      | unit |        | ⬜     |

## Test Results

```
<output from cargo test / test runner>
```

## Risks & Gaps

- **Risk**: <what could still break>
- **Gap**: <what is not tested and why>
";

const STAGE_TEMPLATE_DELIVERY: &str = r"---
task: <task-id>
phase: P5
status: draft
created: __TIMESTAMP__
---

# Delivery: <task-id>

> Final commit + PR + KB promote decisions.

## Commits

| # | Hash | Message |
|---|------|---------|
| 1 |      |         |

## PR

- **Title**:
- **Description**:

## KB Promote

| Knowledge | Kind | Promote? | File |
|-----------|------|----------|------|
|           |      | ⬜       |      |

## Post-Delivery

- [ ] Tests passing
- [ ] Docs updated
- [ ] KB promoted
- [ ] Task archived
";

const STAGE_TEMPLATE_REVIEW: &str = r"---
task: <task-id>
phase: cross-phase
status: draft
created: __TIMESTAMP__
---

# Review Checklist: <task-id>

> **AI pre-fills [ ] — humans tick [x].** AI must never use [x].

## P1: Requirements

- [ ] Requirements are complete and accurate
- [ ] Acceptance criteria are testable
- [ ] Scope boundaries are clear
- [ ] All clarifications resolved

**Gate 1**: ⬜ Approved — AI may proceed to P2 design

---

## P2: Design

- [ ] Approach is sound
- [ ] Trade-offs are documented and acceptable
- [ ] Architecture diagram is clear
- [ ] Files to change are identified

**Gate 2**: ⬜ Approved — AI may proceed to P3 coding

---

## P4: Testing

- [ ] Coverage matrix is complete
- [ ] All tests pass
- [ ] Edge cases covered
- [ ] Risks documented

---

## P5: Delivery

- [ ] All commits have clear messages
- [ ] PR is ready for review
- [ ] KB promotions identified
- [ ] Task can be archived

**Gate 3**: ⬜ Approved — Deliver + Archive task

---

## Final Sign-off

- [ ] All 3 gates approved
- [ ] Task complete
- [ ] Archive ready
";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_stage_skeleton_creates_structure() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        generate_stage_skeleton(root).unwrap();

        assert!(root.join(".enjoyknowledge_stage/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/drafts").exists());
        assert!(root.join(".enjoyknowledge_stage/.archive/tasks").exists());
        assert!(root.join(".enjoyknowledge_stage/tasks/_template").exists());
    }

    #[test]
    fn generate_stage_skeleton_creates_8_templates() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        generate_stage_skeleton(root).unwrap();

        let template_dir = root.join(".enjoyknowledge_stage/tasks/_template");
        for name in &[
            "summary.md",
            "requirements.md",
            "design.md",
            "plan.md",
            "changes.md",
            "tests.md",
            "delivery.md",
            "review.md",
        ] {
            assert!(template_dir.join(name).exists(), "missing template: {name}");
        }
    }

    #[test]
    fn generate_stage_skeleton_templates_idempotent() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        // First run creates templates
        generate_stage_skeleton(root).unwrap();
        let first_size = std::fs::read_to_string(
            root.join(".enjoyknowledge_stage/tasks/_template/summary.md"),
        )
        .unwrap()
        .len();

        // Second run should not overwrite existing templates
        generate_stage_skeleton(root).unwrap();
        let second_size = std::fs::read_to_string(
            root.join(".enjoyknowledge_stage/tasks/_template/summary.md"),
        )
        .unwrap()
        .len();

        assert_eq!(first_size, second_size);
    }

    #[test]
    fn generate_ek_agents_md_produces_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge")).unwrap();

        generate_ek_agents_md(root).unwrap();

        let content =
            std::fs::read_to_string(root.join(".enjoyknowledge/AGENTS.md")).unwrap();
        assert!(content.contains("EnjoyKnowledge KB Index"));
        assert!(content.contains("<!-- enjoyknowledge_KB_INDEX -->"));
        assert!(content.contains("architecture"));
        assert!(content.contains("gotchas"));
        assert!(content.contains("rules"));
        assert!(content.contains("NEVER write to `.enjoyknowledge/` directly"));
    }

    #[test]
    fn generate_stage_agents_md_produces_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join(".enjoyknowledge_stage")).unwrap();

        generate_stage_agents_md(root).unwrap();

        let content =
            std::fs::read_to_string(root.join(".enjoyknowledge_stage/AGENTS.md")).unwrap();
        assert!(content.contains("Stage Writing Spec"));
        assert!(content.contains("8-File System"));
        assert!(content.contains("Hard Gate Protocol"));
        assert!(content.contains("changes.md"));
    }

    #[test]
    fn update_gitignore_adds_rules() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::write(root.join(".gitignore"), "target/\n").unwrap();

        update_gitignore(root).unwrap();

        let content = std::fs::read_to_string(root.join(".gitignore")).unwrap();
        assert!(content.contains(".enjoyknowledge_stage/tasks/*/changes.md"));
        assert!(content.contains(".session/"));
    }

    #[test]
    fn update_gitignore_no_existing_does_not_error() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        update_gitignore(root).unwrap();

        // No .gitignore file should be created if it doesn't exist
        assert!(!root.join(".gitignore").exists());
    }

    #[test]
    fn update_gitignore_idempotent() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        std::fs::write(root.join(".gitignore"), "target/\n").unwrap();

        update_gitignore(root).unwrap();
        let first = std::fs::read_to_string(root.join(".gitignore")).unwrap();

        update_gitignore(root).unwrap();
        let second = std::fs::read_to_string(root.join(".gitignore")).unwrap();

        assert_eq!(first, second);
    }
}
