/// Directory skeleton generation.
use crate::core::Profile;
use std::fmt::Write;
use std::path::Path;

/// Generate the `.enjoyknowledge/` skeleton and `knowledge-tasks/` under `project_root`.
///
/// The skeleton shape is determined by `profile.directories()` and
/// `profile.seed_files()`, so different contexts (coding, design, research, �?
/// produce different directory trees.
pub fn generate_skeleton(project_root: &Path, profile: &dyn Profile) -> anyhow::Result<()> {
    let ek = project_root.join(".enjoyknowledge");
    std::fs::create_dir_all(&ek)?;

    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    for dir in profile.directories() {
        std::fs::create_dir_all(ek.join(dir))?;
    }

    // Write seed files (only if they don't already exist)
    for (rel_path, content) in profile.seed_files() {
        let full = ek.join(rel_path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent)?;
        }
        if !full.exists() {
            let resolved = content.replace("__TIMESTAMP__", &today);
            std::fs::write(&full, resolved)?;
        }
    }

    // knowledge-tasks/ at project root level
    std::fs::create_dir_all(project_root.join("knowledge-tasks"))?;

    // Generate index.md (OKF table of contents)
    let index_path = ek.join("index.md");
    if !index_path.exists() {
        std::fs::write(
            &index_path,
            format!("---\ndescription: Knowledge base index — auto-generated directory of all knowledge files\ntimestamp: {today}\n---\n\n# Knowledge Index\n\n> Auto-generated by enjoyknowledge. Lists all knowledge files.\n"),
        )?;
    }

    Ok(())
}

/// Generate AGENTS.md with the knowledge summary block.
pub fn generate_agents_md(
    project_root: &Path,
    ai_tool: Option<&str>,
    profile: &dyn Profile,
) -> anyhow::Result<()> {
    let content = generate_agents_md_content(ai_tool, profile);
    std::fs::write(project_root.join("AGENTS.md"), content)?;
    Ok(())
}

/// Sync the knowledge summary block in AGENTS.md after a knowledge change (add, fix, etc.).
///
/// This reads the current state via `KnowledgeSource::list_entries` and replaces
/// the content between `<!-- enjoyknowledge_LS_START -->` and
/// `<!-- enjoyknowledge_LS_END -->` in the project root's AGENTS.md.
pub fn sync_agents_md_summary(
    project_root: &Path,
    source: &dyn crate::knowledge::KnowledgeSource,
) -> anyhow::Result<()> {
    let agents_path = project_root.join("AGENTS.md");
    if !agents_path.exists() {
        return Ok(());
    }

    let entries = source.list_entries(None, false)?;
    let summary = format_ls_summary(&entries);

    let content = std::fs::read_to_string(&agents_path)?;
    let start_marker = "<!-- enjoyknowledge_LS_START -->";
    let end_marker = "<!-- enjoyknowledge_LS_END -->";

    let start = match content.find(start_marker) {
        Some(pos) => pos + start_marker.len(),
        None => return Ok(()),
    };
    let Some(end) = content.find(end_marker) else { return Ok(()) };

    let new_content = format!(
        "{}{start_marker}\n{summary}\n{end_marker}{}",
        &content[..start],
        &content[end + end_marker.len()..]
    );

    std::fs::write(&agents_path, new_content)?;
    Ok(())
}

/// Render knowledge entries as a plain-text summary block for AGENTS.md.
fn format_ls_summary(entries: &[crate::knowledge::KnowledgeEntry]) -> String {
    let mut out = String::new();
    for entry in entries {
        if entry.is_dir {
            let _ = writeln!(out, "{}/", entry.path);
        } else {
            match (&entry.description, entry.entry_count) {
                (Some(desc), Some(n)) if n > 1 => {}
                (Some(desc), _) => {
                    let _ = writeln!(out, "  {} �?{}", entry.path, desc);
                }
                _ => {
                    let _ = writeln!(out, "  {}", entry.path);
                }
            }
        }
    }
    out.trim_end().to_string()
}

/// Return AGENTS.md content as a String (used by the template system).
pub fn generate_agents_md_content(ai_tool: Option<&str>, profile: &dyn Profile) -> String {
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    let summary_placeholder = r"<!-- enjoyknowledge_LS_START -->
<!-- Run `enjoyknowledge ls` to populate the knowledge summary. -->
<!-- enjoyknowledge_LS_END -->";

    let label = profile.agents_md_label();
    let tool_label = ai_tool.unwrap_or("AGENTS.md");

    format!(
        r#"# AGENTS.md

This project uses [enjoyknowledge](https://enjoyknowledge.dev) to manage shared context for AI coding tools.

## Knowledge Overview

{summary_placeholder}

Above is the current knowledge base contents. Before starting any coding task, check here to see if relevant knowledge exists.

## Commands

| Command | Why |
|---|---|
| `enjoyknowledge ls` | List files with descriptions �?know what exists without opening files |
| `enjoyknowledge grep <pattern>` | Search inside `##` sections, not raw line numbers |
| `enjoyknowledge cat <path>` | Read a knowledge file (path auto-prefixed with `.enjoyknowledge/`) |
| `enjoyknowledge add <path> "<content>"` | Record a new entry (auto-generates OKF frontmatter) |
| `enjoyknowledge tree` | Recursive directory tree with descriptions |
| `enjoyknowledge doctor` | Health check (5 checks) |
| `enjoyknowledge fix` | Auto-fix common issues |

---
*Generated by enjoyknowledge init (--ai {tool_label}) [{label}] on {today}*
"#
    )
}
